extends@: default

form:
  fields:
    tabs:
      fields:
        advanced:
          fields:
            columns:
              fields:
                column1:
                   fields:

                     header.body_classes:
                       markdown: true
                       description: 'Available classes in Quark Theme (space separated):<br />`header-fixed`, `header-animated`, `header-dark`, `header-transparent`, `sticky-footer`'

                     header.access:
                       type: array
                       label: Permission
                       placeholder_key: key
                       placeholder_value: value(0 or 1)
                       help: 'Insert a key and in value put 1 for true and 0 for false'
                       markdown: true
                       description: 'Available keys: `site.moderador`, `site.colaborador`, `site.parceiro`, `site.cliente`'

                     header.anchors.active:
                       type: toggle
                       label: Active Anchors
                       highlight: 1
                       default: 0
                       help: Active anchors e enable menu sidebar sections
                       options:
                         1: PLUGIN_ADMIN.ENABLED
                         0: PLUGIN_ADMIN.DISABLED
                       validate:
                         type: bool

                     header.tagtitle:
                       type: select
                       label: Anchor TAG
                       classes: fancy
                       default: h2
                       help: (Plugin Anchor) Select the tag title
                       options:
                         h1: H1
                         h2: H2
                         h3: H3
                         h4: H4

                     header.terms:
                       type: text
                       label: Hide Anchor Terms
                       help: (Pligin Anchor) Select the titile you wish hidden. Separete each term with a comma